---
title: "Geographic Computation"
toc: false
listing:
- id: geog
  type: grid
  image-placeholder: placeholder_images/placeholder.png
  contents:
  - ../../docs/geog_374/*/*.ipynb
  categories: true
  fields: [image, title, date, description]
  sort-ui: [title, date]
---

The modules in this unit are **Intermediate** level.  They focus on geographic and geospatial computation.  This section contains material originally built to  support UBC’s **GEOG 374 (Statistics in Geography)**.  This course covers statistical techniques for geography. For economics students, these are a valuable supplement to our intermediate econometrics courses.

These modules in particular are designed to be used in 1 or 2 one-hour long lab environments, with TA or Instructor supervision, or in a flipped classroom setting (i.e. as a lecture)

They include a number of exercises which are intended to be formative (i.e. not graded) in nature, and can be addressed during the lab.

You should make sure you're familiar with the basics of R and using data before starting these notebooks.

## Attribution

:::{.callout-note}
## Suggested Attribution

Hewitt, N., Jerowsky, M., Pierce, K. 2023. _Interactive Notebooks for Statistics and Computation in Geography_. In Adshade et al. 2023. fThe COMET Project\: Creating Online Materials for Econometric Teaching’. `https://comet.arts.ubc.ca/`.
:::

::: {#geog}

:::
