---
title: "Intermediate: Econometrics and Modeling Using R"
toc: false
listing:
- id: intermediate
  type: grid
  image-placeholder: placeholder_images/placeholder.png
  contents:
  - ../../docs/Intermediate/*/*.qmd
  categories: true
  fields: [image, title, date, description]
  sort-ui: [title, date]
- id: geog
  type: grid
  image-placeholder: placeholder_images/placeholder.png
  contents:
  - ../../docs/geog_374/*/*.ipynb
  categories: true
  fields: [image, title, date, description]
  sort-ui: [title, date]
---

The modules in this unit are **Intermediate** level.  They are intended for people who have mastered the basics and are ready to use and `R` for applied econometric modeling.

* If you are looking to filter by a specific course, select the course number in the list of categories on the right.
* If you're looking for projects, check out our [projects page](index_research.qmd) pages for some example and guides.

You should make sure you're familiar with the basics of R and using data before starting these notebooks.  There are also some notebooks that focus on geographic and geospatial computation.  This section contains material originally built to support UBC’s **GEOG 374 (Statistics in Geography)**.  This course covers statistical techniques for geography. For economics students, these are a valuable supplement to our intermediate econometrics courses.

::: {#intermediate}
:::

### Geographic Computation

::: {#geog}
:::