---
title: "Research Projects: Carrying Out An Economic Research Project"
toc: false
listing:
- id: stata
  type: grid
  image-placeholder: placeholder_images/placeholder.png
  contents:
  - ../../docs/5_Research/econ490-stata/*.ipynb
  categories: true
  fields: [image, title, date, description]
  sort-ui: [title, date]
- id: pystata
  type: grid
  image-placeholder: placeholder_images/placeholder.png
  contents:
  - ../../docs/5_Research/econ490-pystata/*.qmd
  categories: true
  fields: [image, title, date, description]
  sort-ui: [title, date]
- id: r
  type: grid
  image-placeholder: placeholder_images/placeholder.png
  contents:
  - ../../docs/5_Research/econ490-r/*.qmd
  categories: true
  fields: [image, title, date, description]
  sort-ui: [title, date]
- id: projects
  type: grid
  image-placeholder: placeholder_images/placeholder.png
  contents:
  - ../../docs/6_Projects/*/*.qmd
  categories: true
  fields: [image, title, date, description]
  sort-ui: [title, date]
---

This section contains material to support UBC's [ECON 490 Seminar in Applied Economics](https://economics.ubc.ca/undergraduate/courses/econ-490-course-information/).  This course is a our senior research class, which focuses on conducting an original research project - including applied econometrics analysis, writing, and presentation.

There are **three versions** of these notebooks: two for STATA, and one for R.

::: {.panel-tabset}
## STATA Notebooks

These notebooks using the STATA programming language, and are launch in Jupyter using the `stata_kernel`.  You will only be able to run these locally, not via most commercial JupyterHubs.

::::::{#stata}
::::::

## R Notebooks

These notebooks are written for the `R` programming language and are launched in Jupyter using the `IRKernel`.

::::::{#r}
::::::

## pystata Notebooks

`pystata` is a Python package that runs STATA code.  So, these are Python notebooks, but they run STATA code.  You will only be able to run these locally, not via most commercial JupyterHubs.

::::::{#pystata}
::::::

:::

## Project Examples

You can also find some of our project example notebooks below.

:::{#projects}
:::