---
title: "COMET Team"
date: 2023-06-27
published-title: Last Updated
title-block-banner: false
filters:
  - collapse-callout
collapse-callout:
  note: true
---

<span style="color:#CC7A00;font-size:18.0pt"> The COMET project is a true team effort; the learning materials that you see here have taken input from many writers, coders, editors, and reviewers from a variety of disciplines. </span>  

> You can contact the COMET team at [comet-project@ubc.ca](mailto:comet-project@ubc.ca)

## Principal Investigators

* [Marina Adshade](https://economics.ubc.ca/profile/marina-adshade/)
* [Jonathan Graves](https://jonathanlgraves.arts.ubc.ca/)
* [Emrul Hasan](https://economics.ubc.ca/profile/emrul-hasan/)

## Research Assistants
:::: {.columns}

::: {.column width="25%"}
<span style="color:#CC7A00"> **2022** </span>  
<li> Colby Chambers </li>
<li> William Co </li>
<li> Paul Corcuera </li>
<li> Rathin Dharani </li>
<li> Anneke Dresselhuis </li>
<li> Colin Grimes</li>
<li> Yeow Chong Goh</li>
<li> Jonah Heyl</li>
<li> Arshiya Malik</li>
<li> Shiming Wu</li>
<li> Oliver Xu</li>
<li> Valeria Zolla </li>

</ul>
:::

::: {.column width="5%"}
<!-- empty column to create gap -->
:::

::: {.column width="70%"}
<span style="color:#CC7A00"> **2023** </span>  
<li> Jasmine Arora </li>
<li> Angela Chen </li>
<li> Anneke Dresselhuis </li>
<li> Priyanshu Mahey </li>
<li> Mridul Manas </li>
<li> Sarthak Kwatra </li>
<li> Giulia Lo Forte </li>
<li> Kady Toure Yeo </li>
<li> Charlotte White </li>
<li> Oliver Xu</li>
:::

:::

## COMET+ Partners

* **UBC's Department of Geography**:  [**Hewitt Lab**](https://blogs.ubc.ca/alpineplants/about-page/) - Nina Hewitt, Mike Jerowsky, and Kevin Pierce
* **UBC's Department of Sociology** and the [**Center for Computational Social Science**](https://ccss.arts.ubc.ca/): [Laura K. Nelson](https://sociology.ubc.ca/profile/laura-nelson/)

## Other Members and Reviewers

* [Paul Schrimpf](https://economics.ubc.ca/profile/paul-schrimpf/)
* [Florian Hoffmann](https://economics.ubc.ca/profile/florian-hoffmann/)
* [Shameem Chowdhury](https://economics.ubc.ca/profile/chowdhury-shameem-mahmoud/)

## Special Thanks

* The [UBC TLEF](https://tlef.ubc.ca/) team, especially [Jeff Miller](https://ctlt.ubc.ca/2022/11/15/jeff-miller/) and [Jason Myers](https://ctlt.ubc.ca/2022/11/15/jason-myers/).
* The team behind [QuantEcon](https://quantecon.org/), especially [Jesse Perla](https://economics.ubc.ca/profile/jesse-perla/) and [Peifan Wu](https://twitter.com/peifanwu) for their advice and support.
* The [UBC CTLT](https://ctlt.ubc.ca/), [Arts ISIT](https://isit.arts.ubc.ca/), and [LT Hub](https://lthub.ubc.ca/) Teams, for their support with Jupyter and GitLab, especially [Stephen Michaud](https://ctlt.ubc.ca/2022/11/09/stephen-michaud/), [Nausheen Shafiq](https://ctlt.ubc.ca/2022/11/03/nausheen-shafiq/), and [Michael Ha](https://www.linkedin.com/in/michaelha/?originalSubdomain=ca).
* The UBC DataScience Slack and the Jupyter team, especially [Tiffany Timbers](https://www.stat.ubc.ca/users/tiffany-timbers), [Phil Austin](https://www.eoas.ubc.ca/people/philaustin), [Firas Moosvi](https://cmps.ok.ubc.ca/about/contact/firas-moosvi/), and the presenters and attendees at JupyterDays 2020
* The staff at the VSE for facilitating events, payments, and space use, especially [Maria Smith](https://economics.ubc.ca/profile/maria-smith/) and [Caroline Gatchalian](https://economics.ubc.ca/profile/caroline-gatchalian/)
* Plus many, many, more!