---
title: COMET Project Presentations and Materials
author: Jonathan Graves
date: last-modified
aliases:
  - ../../dissemination.html
  - ../../dissemination
  - ../dissemination.html
  - ../dissemination
---

Interested in learning more about the COMET project, or teaching and learning with Jupyter?  On this page we have collected some of our presentations, key links, and other materials.

* [2023 UBC TLEF Showcase](2023-TLEF-Poster-Jonathan-Graves.pptx)
* [2024 UBC TLEF Showcase](2024-TLEF-Poster-Jonathan-Graves.pptx)

## CTALE TeachECONference 2024

Are you here from the CTALE TeachECONference 2024?  Here is our presentation and supplemental materials:

* [Presentation](ctale2024/ctale_presentation.qmd)

_Links_:

* [Teaching with Jupyter Notebooks](../teaching_with_comet.qmd)
* [Writing Self-tests](../documentation/writing_self_tests.qmd)
* [Exemplar notebook (Word Embeddings)](../../docs/4_Advanced/advanced_word_embeddings/advanced_word_embeddings_python_version.qmd)
* [Exemplar notebook (clustering)](../../docs/4_Advanced/advanced_classification_and_clustering/advanced_classification_and_clustering.qmd)