
stages:
  - build
  - deploy


#python-prep:
#  stage: prep
#  image: python:latest
#  script:
#   - python --version
#   - pip install requests
#   - python setup.py $KEY $SECRET
#  when: manual
#  artifacts:
#    paths:
#      - comet-quarto

quarto-build:
  stage: build
  image: registry.gitlab.com/quarto-forge/docker/rstats
  script:
  #- apt-get update
  #- apt-get -y install curl
  #- curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
  #- apt-get -y install gdebi-core
  #- gdebi -n quarto-linux-amd64.deb
# - /usr/local/bin/quarto check
  - cd comet-quarto
  - quarto render
  artifacts:
    paths:
    - comet-quarto/_site/

pages:
  stage: deploy
  image: busybox:latest
  script:
  - mv comet-quarto/_site public
  artifacts:
    paths:
    - public
  rules:
  - if: '$CI_COMMIT_BRANCH == "pages"'
  environment:
    name: production
    url: https://comet.arts.ubc.ca