
stages:
  - build
  - deploy


#python-prep:
#  stage: prep
#  image: python:latest
#  script:
#   - python --version
#   - pip install requests
#   - python setup.py $KEY $SECRET
#  when: manual
#  artifacts:
#    paths:
#      - comet-quarto

quarto-build:
  stage: build
  image: repo.code.ubc.ca:5050/arts-isit/tlef/econometrics:latest
  script:
  - micromamba env
  - micromamba activate base
  - quarto check 
  - cd comet-quarto
  - quarto render
  artifacts:
    paths:
    - comet-quarto/_site/

pages:
  stage: deploy
  image: busybox:latest
  script:
  - mv comet-quarto/_site public
  artifacts:
    paths:
    - public
  rules:
  - if: '$CI_COMMIT_BRANCH == "pages"'
  environment:
    name: production
    url: https://comet.arts.ubc.ca