
stages:
  - build
  - render
  - deploy


#python-prep:
#  stage: prep
#  image: python:latest
#  script:
#   - python --version
#   - pip install requests
#   - python setup.py $KEY $SECRET
#  when: manual
#  artifacts:
#    paths:
#      - comet-quarto

quarto-build:
  stage: build
  image: repo.code.ubc.ca:5050/arts-isit/tlef/econometrics:2.0
  script:
  - apt-get update
  - apt-get -y install --no-install-recommends libxtst6
  - apt-get install -y --no-install-recommends libxt6
  - R -e "install.packages('xfun', repos = 'https://mirror.rcg.sfu.ca/mirror/CRAN/')" --no-save
  - R -e "install.packages('vctrs', repos = 'https://mirror.rcg.sfu.ca/mirror/CRAN/')" --no-save
  - R -e "install.packages('rmarkdown', repos = 'https://mirror.rcg.sfu.ca/mirror/CRAN/')" --no-save
  - R -e "install.packages('tidyverse', repos = 'https://mirror.rcg.sfu.ca/mirror/CRAN/')" --no-save
  - apt-get -y install --no-install-recommends libxtst6
  - apt-get install -y --no-install-recommends libxt6
  - quarto check 
  - cd comet-quarto
  - quarto render
  artifacts:
    paths:
    - comet-quarto/_site/

pages:
  stage: deploy
  image: busybox:latest
  script:
  - mv comet-quarto/_site public
  artifacts:
    paths:
    - public
  rules:
  - if: '$CI_COMMIT_BRANCH == "pages"'
  environment:
    name: production
    url: https://comet.arts.ubc.ca