stages:
  - build
  - test
  - deploy

jupyter-build:
  stage: build
  image: python:slim
  script:
    - pip install -U jupyter-book
    - jupyter-book clean comet-home/
    - jupyter-book build comet-home/
  artifacts:
    paths:
      - comet-home/_build/

production:
  stage: deploy
  image: busybox:latest
  script:
    - mv comet-home/_build/html public
  artifacts:
    paths:
      - public
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "pages"'
  environment:
    name: production
    url: https://comet.arts.ubc.ca



test:
    stage: test
    image: busybox:latest
    script:
        - mv comet-home/_build/html public
    artifacts:
        paths:
            - public
    when: manual
    environment:
      name: testing
      url: https://testing-comet.arts.ubc.ca
