
stages:
  - build
  - deploy


#python-prep:
#  stage: prep
#  image: python:latest
#  script:
#   - python --version
#   - pip install requests
#   - python setup.py $KEY $SECRET
#  when: manual
#  artifacts:
#    paths:
#      - comet-quarto

quarto-build:
  stage: build
  image: ubuntu:latest
  script:
  - apt-get update
  - apt-get -y install curl
  - curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
  - apt-get -y install gdebi-core
  - gdebi -n quarto-linux-amd64.deb
# - /usr/local/bin/quarto check
  - apt-get -y install gpg
  - curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > conda.gpg
  - install -o root -g root -m 644 conda.gpg /usr/share/keyrings/conda-archive-keyring.gpg
  - gpg --keyring /usr/share/keyrings/conda-archive-keyring.gpg --no-default-keyring --fingerprint 34161F5BF5EB1D4BFBBB8F0A8AEB4F8B29D82806
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/conda-archive-keyring.gpg] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" > /etc/apt/sources.list.d/conda.list
  - apt update
  - apt install conda
  - source /opt/conda/etc/profile.d/conda.sh
  - conda -V
  - conda create --prefix env 
  - conda activate ./env
  - conda install jupyter
  - conda install -c conda-forge r-base
  - conda install -c conda-forge r-irkernel
  - R -e install.packages('IRkernel')
  - R -e IRkernel::installspec()
  - cd comet-quarto
  - quarto render
  artifacts:
    paths:
    - comet-quarto/_site/

pages:
  stage: deploy
  image: busybox:latest
  script:
  - mv comet-quarto/_site public
  artifacts:
    paths:
    - public
  rules:
  - if: '$CI_COMMIT_BRANCH == "pages"'
  environment:
    name: production
    url: https://comet.arts.ubc.ca