---
title: "Installing for Development"
title-block-banner: false
date: last-modified
published-title: Last Updated
toc: true
---

So, you want to develop and submit new material to COMET? Awesome! The official workflow for hacking on COMET uses VSCode. Other IDEs such as RStudio or Jupyter will also work, but we do not provide official instructions.

1.  First, you will need to install R using your preferred method for your platform. If you’re not sure what this means, follow the instructions on the R website.

2.  Install VSCode using your preferred method for your platform (the linked instructions will be fine for most people). Open VSCode and install the REditorSupport extension, then close VSCode.

3.  Install git using your preferred method for your platform (the linked instructions will be fine for most people). If you are developing on the Github version, you may also wish to install GitHub Desktop.

4.  Finally, install Quarto, and follow the steps to integrate VSCode.

5.  Open an R terminal and install `renv` by runnning `install.packages("renv")`.

6.  Use git to clone the COMET repository and open it in VSCode. A popup should ask you to install languageserver, click yes.

7.  When Step 6 is complete, restart VSCode. Clone the COMET repository folder and open it. Select the terminal option in the bottom panel and choose “R Terminal” in the dropdown menu next to the plus sign.

8.  In the VSCode terminal, run `renv::restore()`, and type Y to accept installing the packages.

Congratulations, you’re ready to run and hack on all of the COMET notebooks!