---
title: "Work-Learn Application Tips"
date: 2023-4-02
title-block-banner: true
---

Are you interested in joining the COMET project as a Work-Learn student or other student?  Check out these tips to improve your chance of getting an interview.

1.  **Submit all requested documentation.**  It sounds simple but over 60% of the applications we received did not include at least one of the requested documents.  In addition to your application being incomplete, it also indicates low attention to detail and will lead to your application we rejected automatically.
2.  **Use a cover letter effectively.**  There is a general sense among some people that a cover letter is pointless, given a resume.  This might be true for more senior positions, but we request them for a reason: they are your opportunity to help use contextualize your resume and other information.  Use a cover letter to:
  * Point out key ways you meet the job description, especially if your resume is long or complex
  * Address any issues or points that might raise a question in the reviewer's mind (e.g., a failed course in a key area)
  * Highlight any unique qualifications or experiences that might not come through on a resume.  This is particularly import for some jobs, particularly those that are looking for diverse experiences or backgrounds.
3. **Tailor your resume.**  Spend a few minutes specifying jobs and tasks so that they focus on the job being applied for.  We received a large number of resumes from students in sciences or engineering which outlined skills like "titrating reaction reagents" or "3D drafting using AutoCAD" for a data analytics position.  These simply aren't relevant, and clutter your resume.  They also indicate a poor attention to detail or lack of understanding about what the job is looking for.
  * I recommend keeping a "main" version of your resume with all the details, then cutting it down when applying.  This will save you time.  You can also save a couple "versions" for certain types of jobs.
4.  **Don't add cruft to your resume.**  This happens a lot with computer science skills and "projects": we aren't particularly interested in your blackjack simulation your wrote in Javascript, or your term project using R in STAT 200.  Adding these things dilutes any real experiences you have.  A good rule of thumb is that a project should be significant in scope and demonstrate multiple skills.  Hackathons or theses are good examples of thing you _should_ add.  A regular course project is not.
  * If you _really_ want to add stuff from a course, include it as "Relevant courses" under education with short descriptions.