name: Build and Extract Artifacts
on:
  push:
    branches:
      - pages_build
  pull_request:
    branches:
      - pages_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .dockerfile
        tags: my-app-image:latest
        outputs: type=local,dest=./artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: artifacts/artifacts/build
