name: Test Build and Push to Docker Hub

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Quarto Notebooks
        id: lint
        run: |
          find ./project/docs/ -name "*.qmd" -type f -exec python meta/testing/linter.py {} \; > lint_output.txt
          if [ -s lint_output.txt ]; then
            echo "linting_failed=true" >> $GITHUB_OUTPUT
            cat lint_output.txt
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sub_new image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: sub_new.dockerfile
          push: true
          tags: alexr951/testing_comet:sub_new

      - name: Build and push main image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .dockerfile
          push: true
          tags: alexr951/testing_comet:latest

      - name: Test main image
        run: |
          docker run --rm alexr951/testing_comet:latest ls /
          mkdir -p ./artifacts
          docker cp $(docker create --rm alexr951/testing_comet:latest):/ ./artifacts

      - name: Display structure of artifacts
        run: ls -R ./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Render
          path: ./artifacts
          retention-days: 5
