name: Test Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Quarto Notebooks
        id: lint
        run: |
          find ./project/docs/ -name "*.qmd" -type f -exec python meta/testing/linter.py {} \; > lint_output.txt
          if [ -s lint_output.txt ]; then
            echo "linting_failed=true" >> $GITHUB_OUTPUT
            cat lint_output.txt
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .dockerfile
          tags: my-app-image:latest
          outputs: type=local,dest=./artifacts

      - name: Display structure of downloaded files
        run: ls -R ./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Render
          path: ./artifacts
          retention-days: 5
