name: Test Build for New Dockerfile (02-06-2025)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Quarto Notebooks
        id: lint
        run: |
          find ./project/docs/ -name "*.qmd" -type f -exec python meta/testing/linter.py {} \; > lint_output.txt
          if [ -s lint_output.txt ]; then
            echo "linting_failed=true" >> $GITHUB_OUTPUT
            cat lint_output.txt
            exit 1
          fi

      - name: Build main image
        run: docker build -t my-app-image:latest -f .dockerfile .

      - name: Test main image
        run: |
          docker run --rm my-app-image:latest ls /
          mkdir -p ./artifacts
          docker cp $(docker create --rm my-app-image:latest):/ ./artifacts

      - name: Display structure of artifacts
        run: ls -R ./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Render
          path: ./artifacts
          retention-days: 5